### ISSUE TITLE
Make test case from README.md example

### ISSUE THREAD

**Issue by elisno** [SciML/QuantumNLDiffEq.jl#3]
~~I cannot reproduce this plot from the current example.~~
I can reproduce the plot from the MWE after updating Yao.jl (see https://github.com/SciML/QuantumNLDiffEq.jl/issues/3#issuecomment-1079982349)

It would be nice to make a test case that reproduces the plot, or rather the resulting expectation values.

# MWE
```julia
julia> begin
           using Yao, QuantumNLDiffEq
           M = range(start=0; stop=0.9, length=20)
           cost = sum([put(6, i=>Z) for i in 1:6])
           var = dispatch(EasyBuild.variational_circuit(6,5), :random)
           quantum_feature_map_circuit = chain(6, [put(i=>Ry(0)) for i in 1:6])
           params = parameters(var)
           u_0 = 1.0
           N = 6
       end
       
julia> train!(quantum_feature_map_circuit, cost, var, M, N, 1.0, params)

julia> e = [expect(cost, zero_state(N)=>QuantumNLDiffEq.new_circuit(quantum_feature_map_circuit, var, i, params, N; mapping=QuantumNLDiffEq.Chebyshev())) .+ u_0 .- expect(cost, zero_state(N)=>QuantumNLDiffEq.new_circuit(quantum_feature_map_circuit, var, M[1], params, N; mapping=QuantumNLDiffEq.Chebyshev()))  for i in M]

julia> import Plots

julia> Plots.plot(M, real.(e))
```

# Expected plot
![download](https://user-images.githubusercontent.com/51269425/160281466-ced2acc9-fb2e-4ad0-a23a-4bc1dfd934a9.svg)

# Actual plot
![download](https://user-images.githubusercontent.com/18127060/160288840-2487c017-b34f-4743-83f2-82111b557523.png)

_Originally posted by @elisno in https://github.com/SciML/QuantumNLDiffEq.jl/pull/1#discussion_r835925088_

**Comment by elisno** [comment]
@VarLad Can you share any references for the circuit that you are trying to optimize here?

**Comment by VarLad** [comment]
@elisno Its currently broken and will be fixed after an update from Yao :)

**Comment by elisno** [comment]
You're right. I managed to reproduce the expected plot from the MWE after checking out the master-branch of Yao.jl.

```bash
(QuantumNLDiffEq) pkg> st
     Project QuantumNLDiffEq v0.0.1
      Status `/workspaces/QuantumNLDiffEq.jl/Project.toml`
  [587475ba] Flux v0.12.9
  [91a5bcdd] Plots v1.27.3
  [5872b779] Yao v0.7.1 `https://github.com/QuantumBFS/Yao.jl.git#master`
  [418bc28f] YaoBlocks v0.12.1 `https://github.com/QuantumBFS/Yao.jl.git:lib/YaoBlocks#master`
  [e88e6eb3] Zygote v0.6.37
```

**Comment by elisno** [comment]
Adding a test for this should resolve the issue. I'll keep it open for now.

**Comment by VarLad** [comment]
@elisno I've added it to README.md already though :stuck_out_tongue:

**Comment by elisno** [comment]
Fair enough 😄, but the installation instructions omitted the fact that `Yao.jl#master` was required.

The broken plot was based on `YaoBlocks#master`, but `Yao v0.7.1`.

---

Everything works after adding

```julia-repl
pkg> add Yao#master
```

**Comment by VarLad** [comment]
@elisno Sorry, I'm not sure if Yao#master is need :sweat_smile: 
I'd pull in the stable version of Yao though.

**Comment by elisno** [comment]
@VarLad I think you can link a #1 to this issue in the PR description.
```
Fixes #3
```

**Comment by VarLad** [comment]
@elisno I think this issue is resolved since Yao released a new version

**Comment by elisno** [comment]
> @elisno I think this issue is resolved since Yao released a new version

Yes you're right. I closed the associated PR once you updated the tests. I forgot this issue in the cleanup.
